[package]
name = "server"
authors = ["ge:org"]
version.workspace = true
edition.workspace = true

[dependencies]
actix-files = "0.6.6"
actix-web = "4.9.0"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
terminal-link = "0.1.0"
