[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.server]
command = "cargo"
args = ["run"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.client]
script = "cd ../client/ && bun run build"

[tasks.run]
dependencies = ["client", "server"]
